### ISSUE TITLE
Stylesheet file naming convention

### ISSUE THREAD

**Issue by mpdaly** [OrdnanceSurvey/osngd-resources#1]
The **OS NGD API - Features** [uses](https://osdatahub.os.uk/docs/ofa/technicalSpecification) `theme-collection-featuretype` naming convention, eg `bld-fts-buildingline`, but this repo uses `theme_collection_featuretype`, eg, `bld_fts_buildingline.sld`.

Could they be made the same, for consistency (and to make lookups easier)?

**Comment by robertdlangford** [comment]
Thanks for the feedback @mpdaly. The initial resources have been developed to support the download variants that you can request via OS Select+Build.
The conflict arises as hyphens can cause issues in GeoPackage and database naming conventions.  Conversely underscores can cause issues in API environments, as they do not appear in URLs very well (easy to misinterpret and typo) and they get hidden when turned into a hyperlink.
Which is why both variations exist depending on your access method. If you have any further suggestions how we could improve our resources, please do not hesitate to get in touch.
